version: 2

models:
  - name: fact_order_items
    description: Fact table with granularity at the order item level.
    columns:
      - name: order_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: price
        tests: [not_null]
      - name: freight_value
        tests: [not_null]

  - name: fact_reviews
    description: Fact table for customer reviews per order.
    columns:
      - name: order_id
        tests: [not_null]
      - name: review_score
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5]

  - name: fact_payments
    description: Fact table for payment transactions per order.
    columns:
      - name: order_id
        tests: [not_null]
      - name: payment_type
        tests: [not_null]
      - name: payment_value
        tests: [not_null]
        meta:
          comment: 'Ensure payment values are non-negative'