version: 2

models:
  - name: dim_customers
    description: Dimension table for customer-level attributes.
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: customer_state
        tests:
          - accepted_values:
              values: ['AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 'RS', 'SC', 'SE', 'SP', 'TO']

  - name: dim_orders
    description: Dimension table for order-level metadata and timestamps.
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]

  - name: dim_products
    description: Dimension table for product-level attributes.
    columns:
      - name: product_id
        tests: [not_null, unique]
      - name: product_category_name
        tests: [not_null]

  - name: dim_sellers
    description: Dimension table for seller attributes and location.
    columns:
      - name: seller_id
        tests: [not_null, unique]

  - name: dim_dates
    description: Date dimension generated from order timestamps.
    columns:
      - name: date
        tests: [not_null, unique]
